// <auto-generated />
using System;
using ConfigureServices;
using ConfigureServices.Models.Fields;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ConfigureServices.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ConfigureServices.Models.ComplexModels.ComplexModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_complexmodels");

                    b.ToTable("complexmodels");
                });

            modelBuilder.Entity("ConfigureServices.Models.ComplexModels.SimpleModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("AttributeId")
                        .HasColumnType("bigint")
                        .HasColumnName("attributeid");

                    b.Property<long?>("ComplexModelId")
                        .HasColumnType("bigint")
                        .HasColumnName("complexmodelid");

                    b.Property<BaseField>("Field")
                        .HasColumnType("jsonb")
                        .HasColumnName("field");

                    b.HasKey("Id")
                        .HasName("pk_simplemodel");

                    b.HasIndex("ComplexModelId")
                        .HasDatabaseName("ix_simplemodel_complexmodelid");

                    b.ToTable("simplemodel");
                });

            modelBuilder.Entity("ConfigureServices.Models.ComplexModels.SimpleModel", b =>
                {
                    b.HasOne("ConfigureServices.Models.ComplexModels.ComplexModel", null)
                        .WithMany("AttributeValues")
                        .HasForeignKey("ComplexModelId")
                        .HasConstraintName("fk_simplemodel_complexmodels_complexmodelid");
                });

            modelBuilder.Entity("ConfigureServices.Models.ComplexModels.ComplexModel", b =>
                {
                    b.Navigation("AttributeValues");
                });
#pragma warning restore 612, 618
        }
    }
}
